### ISSUE TITLE
“ua status” crashes (status.py, line 217, in format_tabular)

### ISSUE THREAD

**Issue by matthewpaulthomas** [CanonicalLtd/ubuntu-advantage-client#1000]
ua 19.6~ubuntu14.04.4

1\. `ua status`

What happens:
```
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.6', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 506, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 541, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 432, in action_status
    output = ua_status.format_tabular(cfg.status())
  File "/usr/lib/python3/dist-packages/uaclient/status.py", line 217, in format_tabular
    "description": service_status["description"],
KeyError: 'description'
```

**Comment by powersj** [comment]
@matthewpaulthomas 

* When you got this stack trace were you attached? Unattached?
* Was this in a container, a VM, baremetal?
* Is it always happening?
* If attached, if you detach and reattach, does it still happen?

**Comment by matthewpaulthomas** [comment]
>- When you got this stack trace were you attached? Unattached?

Attached:
```
 😌 11:28:25@~> sudo ua attach
This machine is already attached to 'mpt@_________.___'.
```

> - Was this in a container, a VM, baremetal?

Bare metal

> - Is it always happening?

Yes. I remember running `ua status` successfully late last year, but since reporting this, it’s always crashed.

> - If attached, if you detach and reattach, does it still happen?

I can’t tell, because detaching crashes too:
```
Detach will disable the following service:
    esm-infra
Are you sure? (y/N) y
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.6', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 506, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 541, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 51, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 74, in new_f
    return f(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 294, in action_detach
    ent.disable(silent=True)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 91, in disable
    self._cleanup()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 96, in _cleanup
    self.remove_apt_config()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 267, in remove_apt_config
    "machine-access-{}".format(self.name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by matthewpaulthomas** [comment]
Ohhhh, interesting. Trying to re-enable ESM, UA claims it’s “already enabled”, but then `status` and `detach` both resume working:
```
 😌 11:28:58@~> sudo ua enable esm
Cannot enable 'esm'
For a list of services see: sudo ua status
 😠 11:36:13@~> sudo ua enable esm-infra
One moment, checking your subscription first
Updating 'esm-infra' apt sources list on changed directives.
Updating package lists
Updating package lists
ESM Infra is already enabled.
See: sudo ua status
 😠 11:36:55@~> ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        yes       n/a       Common Criteria EAL2 Provisioning Packages
cis-audit     no        —         Center for Internet Security Audit Tools
esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
fips          yes       n/a       NIST-certified FIPS modules
fips-updates  yes       n/a       Uncertified security updates to FIPS modules
livepatch     yes       n/a       Canonical Livepatch service

Enable services with: ua enable <service>

     Account: mpt@_________.___
Subscription: mpt@_________.___
 😌 11:37:02@~> sudo ua detach
Detach will disable the following service:
    esm-infra
Are you sure? (y/N) y
Updating package lists
This machine is now detached
```

So, I think this is a side-effect of renaming `esm` to `esm-infra` — `ua` looks at the list of entitlements and sees something called `esm` that it doesn’t (any longer) recognise.

I think this supports that hypothesis:
```
 😌 11:46:28@~> cd /usr/lib/python3/dist-packages/uaclient/
 😌 11:46:41@uaclient> grep -r esm *
config.py:        "machine-access-esm-infra": DataPath(
config.py:            "machine-access-esm-infra.json", True
entitlements/esm.py:    help_doc_url = "https://ubuntu.com/esm"
entitlements/esm.py:    name = "esm-infra"
entitlements/esm.py:    repo_url = "https://esm.ubuntu.com"
entitlements/esm.py:    repo_key_file = "ubuntu-advantage-esm-infra-trusty.gpg"
entitlements/__init__.py:from uaclient.entitlements.esm import ESMEntitlement
Binary file entitlements/__pycache__/fips.cpython-34.pyc matches
Binary file entitlements/__pycache__/__init__.cpython-34.pyc matches
Binary file entitlements/__pycache__/esm.cpython-34.pyc matches
entitlements/fips.py:    repo_url = "https://esm.ubuntu.com/fips"
entitlements/fips.py:    repo_url = "https://esm.ubuntu.com/fips-updates"
Binary file __pycache__/config.cpython-34.pyc matches
 😌 11:46:45@uaclient>
```
So the code understands `esm-infra`, but contains nothing to understand the legacy `esm`.

If so, this problem will affect everyone who subscribed before `esm` was renamed.

**Comment by powersj** [comment]
Thanks for the follow up.

You are correct that the rename would be the cause here. The new UA client was never officially released until after the rename. Therefore, I only expect internal users who used the client during development to have seen this.

While annoying, I do not think there is any action here, so marking this closed.
