### ISSUE TITLE
FTBFS in Xenial, Bionic, Cosmic, and Disco

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#170]
Build Logs:
- [Xenial](https://launchpadlibrarian.net/414294440/buildlog.txt.gz)
- [Bionic](https://launchpadlibrarian.net/414294433/buildlog.txt.gz)
- [Cosmic](https://launchpadlibrarian.net/414294432/buildlog.txt.gz)
- [Disco](https://launchpadlibrarian.net/414294439/buildlog.txt.gz)

Same traceback in all releases:
```shell
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from uaclient import config
  File "/home/buildd/work/tree/recipe/uaclient/config.py", line 7, in <module>
    import yaml
ImportError: No module named 'yaml'
E: pybuild pybuild:274: clean: plugin distutils failed with: exit code=1: python3.5 setup.py clean 
```

**Comment by powersj** [comment]
Looks like adding `python3-setuptools` and `python3-yaml` resolved it locally for me.

**Comment by powersj** [comment]
This is resolved. Once we do an upload to Trusty the MIRs for macaroon support will close and we will have a fully working build there as well.
