### ISSUE TITLE
ua detach causes traceback in get_motd_status

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#196]
`get_motd_summary` should properly return empty string on detached status.

possibly `cfg.is_attached` is not properly reporting false during 'detach' due to caching of `Config.machine_token`.

```pytb
[DEBUG]: File does not exist: /var/lib/ubuntu-advantage/account-contracts.json
Traceback (most recent call last):
  File "/usr/bin/ua", line 11, in <module>
    load_entry_point('ubuntu-advantage-tools==19.1', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 373, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 197, in action_detach
    ua_status.write_motd_summary(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/status.py", line 114, in write_motd_summary
    ua_motd_status = get_motd_summary(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/status.py", line 139, in get_motd_summary
    contractInfo = cfg.contracts['contracts'][0]['contractInfo']
TypeError: list indices must be integers or slices, not str
```

**Comment by OddBloke** [comment]
I believe Chad is correct: `UAConfig.is_attached` just does `return bool(self.machine_token)`, and `self.machine_token` will use `self._machine_token` if it is set. `UAConfig.delete_cache` does not clear this in-memory cache (or the corresponding in-memory caches `self._contracts` and `self._entitlements`).
