### ISSUE TITLE
PPA builds failing due to changes in #185

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#197]
See https://launchpad.net/~canonical-server/+archive/ubuntu/ua-client-daily/+build/16516566:

```
python3 -m unittest discover uaclient
...............E..........
======================================================================
ERROR: tests.test_cli_attach (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.test_cli_attach
Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/<<PKGBUILDDIR>>/uaclient/tests/test_cli_attach.py", line 6, in <module>
    from uaclient.cli import action_attach
  File "/<<PKGBUILDDIR>>/uaclient/cli.py", line 25, in <module>
    from uaclient import sso
  File "/<<PKGBUILDDIR>>/uaclient/sso.py", line 5, in <module>
    import pymacaroons
ModuleNotFoundError: No module named 'pymacaroons'


----------------------------------------------------------------------
Ran 26 tests in 0.019s

FAILED (errors=1)
```

**Comment by OddBloke** [comment]
I believe #198 will fix this, but didn't use the metadata to auto-close because I want to see a PPA build pass before closing this out.

**Comment by OddBloke** [comment]
#198 had an incorrect package name, which was fixed in #199. This revealed that there are lint errors on xenial (we run flake8 during package build), which should be fixed by #200 (which also introduces tox environments to help avoid this in future).

(The lint errors would also have been present on trusty, but we don't yet have a python3-pymacaroons package in trusty, so we didn't even get that far.)

**Comment by OddBloke** [comment]
I've filed #201 for the trusty pymacaroons issue, as that's a separate fix from this issue.

**Comment by OddBloke** [comment]
We have successful builds in https://code.launchpad.net/~canonical-server/+recipe/ua-client-daily, except for the expected trusty failure. Closing this.
