### ISSUE TITLE
fails to run on trusty: libnacl too new

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#243]
```ubuntu@trusty-ua:~$ ua
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (libnacl 1.4.5 (/usr/lib/python3/dist-packages), Requirement.parse('libnacl>=1.3.6,<1.4'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ua", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: libnacl>=1.3.6,<1.4
```
This seems to come from python3-pymacaroons' requirements:
```
$ cat /usr/lib/python3/dist-packages/pymacaroons-0.9.2.egg-info/requires.txt
six>=1.8.0
libnacl>=1.3.6,<1.4
```
Which in turn is defined in its `setup.py`:
```python
    install_requires=[
        'six>=1.8.0',
        'libnacl>=1.3.6,<1.4',
    ],
```

This was changed upstream in https://github.com/ecordell/pymacaroons/issues/21 via https://github.com/ecordell/pymacaroons/commit/623cc1de83ee5258868d48a50743caf2de83f624:
```diff
--- a/setup.py
+++ b/setup.py
@@ -26,7 +26,7 @@ def read_file(*paths):
     long_description=long_description,
     install_requires=[
         'six>=1.8.0',
-        'libnacl>=1.3.6,<1.5',
+        'libnacl>=1.3.6,<1.6',
     ],
     classifiers=[
         'Development Status :: 4 - Beta',
```

**Comment by panlinux** [comment]
This is being addressed in the pymacaroons package in Ubuntu, nothing to do in ua itself.
