### ISSUE TITLE
fails to run on trusty: python3-six too old

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#246]
After fixing issue #243 , I hit another version check failure on trusty:
```
$ ua
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (six 1.5.2 (/usr/lib/python3/dist-packages), Requirement.parse('six>=1.8.0'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ua", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: six>=1.8.0
```

Trusty has pyton3-six 1.5.2, and python3-pymacaroons wants 1.8.0 or higher.

**Comment by panlinux** [comment]
This is being addressed in the pymacaroons package in Ubuntu, nothing to do in ua itself.
