### ISSUE TITLE
enabling livepatch on trusty doesn't install snapd

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#266]
It seems like ua is expecting snapd to be already installed:
```
ubuntu@trusty-ua:~$ sudo ua --debug enable livepatch
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-token.json
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-access-livepatch.json
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-access-esm.json
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-access-support
[DEBUG]: Reading file: /etc/os-release
[DEBUG]: Livepatch not enabled. Invalid command specified '/snap/bin/canonical-livepatch status'.
Installing canonical-livepatch snap...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 158, in subp
    bytes_args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: b'snap'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.1', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 374, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 177, in action_enable
    return 0 if entitlement.enable() else 1
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/livepatch.py", line 77, in enable
    util.subp(['snap', 'install', 'canonical-livepatch'], capture=True)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 167, in subp
    raise ProcessExecutionError(cmd=' '.join(args))
uaclient.util.ProcessExecutionError: Invalid command specified 'snap install canonical-livepatch'.
```
I don't have it installed:
```
ubuntu@trusty-ua:~$ apt-cache policy snapd
snapd:
  Installed: (none)
  Candidate: 2.38~14.04
  Version table:
     2.38~14.04 0
        500 http://br.archive.ubuntu.com/ubuntu/ trusty-proposed/main amd64 Packages
     2.37.4~14.04.1 0
        500 http://br.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
ubuntu@trusty-ua:~$ 
```

**Comment by panlinux** [comment]
Note that installing snapd will bring in a new kernel for trusty (snapd needs an hwe kernel), which means a reboot is needed before livepatch can be used. The old shell client handled that, maybe we can adopt that behavior.

**Comment by panlinux** [comment]
For example, after I manually install snapd on this trusty vm, and try to enable livepatch again, it still fails, exactly because of the old running kernel:
```
ubuntu@trusty-ua:~$ sudo ua --debug enable livepatch
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-token.json
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-access-support
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-access-esm.json
[DEBUG]: Reading file: /var/lib/ubuntu-advantage/machine-access-livepatch.json
[DEBUG]: Reading file: /etc/os-release
[DEBUG]: Livepatch not enabled. Invalid command specified '/snap/bin/canonical-livepatch status'.
Installing canonical-livepatch snap...
[ERROR]: Failed running cmd: snap install canonical-livepatch, rc: 1 stderr: b'error: system does not fully support snapd: you need to reboot into a 4.4\n       kernel to start using snapd\n'
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.1', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 374, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 177, in action_enable
    return 0 if entitlement.enable() else 1
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/livepatch.py", line 77, in enable
    util.subp(['snap', 'install', 'canonical-livepatch'], capture=True)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 174, in subp
    stderr=err)
uaclient.util.ProcessExecutionError: Failed running command 'snap install canonical-livepatch' [exit(1)]. Message: b'error: system does not fully support snapd: you need to reboot into a 4.4\n       kernel to start using snapd\n'
```
