### ISSUE TITLE
Traceback if a config file without a `log_level` used

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#406]
With this config file:

```yaml
# Development UA Client config file. YAML
sso_auth_url: 'https://login.ubuntu.com'
contract_url: 'https://contracts.staging.canonical.com'
data_dir: /tmp/uaclient
log_file: ubuntu-advantage-devel.log
```

I see this traceback:

```pytb
$ UA_CONFIG_FILE=conf2 ua attach
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 396, in main
    cfg = config.UAConfig()
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 54, in __init__
    self.cfg = parse_config()
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 271, in parse_config
    cfg['log_level'] = cfg['log_level'].upper()
AttributeError: 'int' object has no attribute 'upper'
```

This also occurs if `UA_CONFIG_FILE` points at a non-existent config file (i.e. `$ UA_CONFIG_FILE=nope ua attach`).

**Comment by OddBloke** [comment]
(I don't believe this is a blocker because (a) it only occurs if someone is not using the default configuration, and (b) it's a result of misconfiguration which can easily be remedied.)

FAOD, the workaround is to add `log_level: error` to your config file.
