### ISSUE TITLE
ubuntu-advantage client in disco traces on attach

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#514]
$ sudo ua attach <contractToken>

This machine is now attached to 'chad.smith@canonical.com'.

Traceback (most recent call last):
  File "/usr/bin/ua", line 11, in <module>
    load_entry_point('ubuntu-advantage-tools==19.2', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 371, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 241, in action_attach
    action_status(args=None, cfg=cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 295, in action_status
    contractInfo['effectiveTo'], '%Y-%m-%dT%H:%M:%SZ')
KeyError: 'effectiveTo'

**Comment by blackboxsw** [comment]
the backend dropped the effectiveTo key for the free contract (which doesn't expire). This is already handled by uaclient tip.

**Comment by panlinux** [comment]
This is ubuntu specific, disco-only.

**Comment by panlinux** [comment]
This is being handled in https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1829788
