### ISSUE TITLE
fips-updates repo has a xenial-updates pocket but no xenial pocket, causing failure to enable

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#571]
```pytb
$ UA_CONFIG_FILE=conf sudo -E ua enable fips-updates
Enabling authenticated repo: https://esm.staging.ubuntu.com/fips-updates
Updating package lists ...
ERROR: Failed running command 'apt-get update' [exit(100)]. Message: b"W: The repository 'https://esm.staging.ubuntu.com/fips-updates/ubuntu xenial Release' does not have a Release file.\nE: Failed to fetch https://esm.staging.ubuntu.com/fips-updates/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found\nE: Some index files failed to download. They have been ignored, or old ones used instead.\n"
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 387, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 416, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 59, in wrapper
    return func(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 217, in action_enable
    return 0 if _perform_enable(args.name, cfg) else 1
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 203, in _perform_enable
    ret = entitlement.enable(silent_if_inapplicable=silent_if_inapplicable)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 73, in enable
    if not self.setup_apt_config():
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 237, in setup_apt_config
    ['apt-get', 'update'], capture=True, retry_sleeps=APT_RETRIES)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 253, in subp
    out, err = _subp(args, rcs, capture)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 226, in _subp
    stderr=err)
uaclient.util.ProcessExecutionError: Failed running command 'apt-get update' [exit(100)]. Message: b"W: The repository 'https://esm.staging.ubuntu.com/fips-updates/ubuntu xenial Release' does not have a Release file.\nE: Failed to fetch https://esm.staging.ubuntu.com/fips-updates/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found\nE: Some index files failed to download. They have been ignored, or old ones used instead.\n"
```

```
$ curl -I https://esm.staging.ubuntu.com/fips-updates/ubuntu/dists/xenial/main/binary-amd64/Packages 
HTTP/1.1 404 Not Found
...
```

```
$ curl -I https://esm.staging.ubuntu.com/fips-updates/ubuntu/dists/xenial-updates/main/binary-amd64/Packages 
HTTP/1.1 200 OK
...
```

**Comment by OddBloke** [comment]
I believe this is because the contract server is incorrectly instructing us to use `xenial` as the suite, instead of `xenial-updates`. The relevant part of `machine-access-fips-updates.json:`

```json
        "directives": {
            "suites": [
                "xenial"
            ],
            "aptKey": "B220D065",
            "additionalPackages": null,
            "aptURL": "https://esm.staging.ubuntu.com/fips-updates"
        },
```

**Comment by OddBloke** [comment]
For comparison, ESM _does_ specify `$suite-updates`:

```json
        "directives": {
            "suites": [
                "precise",
                "trusty-security",
                "trusty-updates"
            ],
            "aptKey": "B220D065",
            "additionalPackages": null,
            "aptURL": "https://esm.staging.ubuntu.com"
        },
```

**Comment by OddBloke** [comment]
I've filed https://github.com/CanonicalLtd/ua-contracts/issues/308 against ua-contracts to address this on the server side.

**Comment by OddBloke** [comment]
This is reportedly fixed in ua-contracts (thanks @frankban!); now blocked on having a contract which is entitled to FIPS Updates for testing.

**Comment by OddBloke** [comment]
I have validated that this is fixed.
