### ISSUE TITLE
attach fails if apt is busy

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#629]
When attaching, if apt is busy doing something else, we get a big traceback. What can we do to catch this and clean this up? This might go nicely with the apt retry branch.

```shell
multipass@test:~$ sudo ua attach <token>
Enabling default service esm
Enabling authenticated repo: https://esm.ubuntu.com
Updating package lists
ERROR: Failed running command 'apt-get update' [exit(100)]. Message: b'E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)\nE: Unable to lock directory /var/lib/apt/lists/\n'
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 394, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 423, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 268, in action_attach
    cfg, contract_token, allow_enable=True):
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 267, in request_updated_contract
    allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 219, in process_entitlement_delta
    orig_access, deltas, allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 142, in process_contract_deltas
    if super().process_contract_deltas(orig_access, deltas, allow_enable):
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/base.py", line 271, in process_contract_deltas
    self.enable()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 73, in enable
    if not self.setup_apt_config():
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 237, in setup_apt_config
    ['apt-get', 'update'], capture=True, retry_sleeps=APT_RETRIES)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 265, in subp
    out, err = _subp(args, rcs, capture)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 238, in _subp
    stderr=err)
uaclient.util.ProcessExecutionError: Failed running command 'apt-get update' [exit(100)]. Message: b'E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)\nE: Unable to lock directory /var/lib/apt/lists/\n'
multipass@test:~$ 
```

**Comment by blackboxsw** [comment]
we currently retry 3 times at 
APT_RETRIES = [1.0, 10.0, 10.0]

for reference charmhelpers lib does the following:
APT_NO_LOCK_RETRY_DELAY = 10  # Wait 10 seconds between apt lock checks.
APT_NO_LOCK_RETRY_COUNT = 30  # Retry to acquire the lock X times.

We could easily make this retry loop longer  and improve the error mesage so it's not a nasty traceback

**Comment by blackboxsw** [comment]
We will clean up this traceback message so it's more easily understood and actionable by the user. But, we would like to continue with this short retry timeout because we expect the user to be sitting at the console in most cases, so a quick feedback loop here will allow them to correct the apt lock issue if needed (or at least validate that unattended upgrades has commpleted before enabling/attaching again.

For the case where #cloud-config is performing an unattended upgrade here, we can instrument additional retries up in cloud-init to ensure we wait an adequate amount of time for an unattending UA install/attach/enable

**Comment by OddBloke** [comment]
(I've filed the different timeout behaviour as #642.)
