### ISSUE TITLE
Traceback when running `ua enable fips`

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#664]
```pytb
$ sudo ua enable fips
Refreshing contracts prior to enable
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 397, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 426, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 60, in wrapper
    return func(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 219, in action_enable
    if not contract.request_updated_contract(cfg):
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 267, in request_updated_contract
    allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 219, in process_entitlement_delta
    orig_access, deltas, allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 136, in process_contract_deltas
    if super().process_contract_deltas(orig_access, deltas, allow_enable):
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/base.py", line 229, in process_contract_deltas
    util.apply_series_overrides(deltas)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 397, in apply_series_overrides
    orig_access['entitlement'][key].update(value)
KeyError: 'directives'
```

**Comment by OddBloke** [comment]
I'm going to look in to this right now, in case this is a bug that will also affect trusty.
