### ISSUE TITLE
ua enable apt services fail handling tempfile cleanup when network is down

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#755]
on a trusty lxc without network, traceback seen on **ua enable esm**
```
 root@dev-t:~# ip link set dev eth0 down
root@dev-t:~# ua enable esm
One moment, checking your subscription first
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 61, in assert_valid_apt_credentials
    timeout=APT_HELPER_TIMEOUT,
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 364, in subp
    out, err = _subp(args, rcs, capture, timeout)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 324, in _subp
    stderr=err.decode("utf-8"),
uaclient.util.ProcessExecutionError: Failed running command '/usr/lib/apt/apt-helper download-file https://bearer:mAgJhAwoQMjJOVFJCJIzpSprhF6O_4BIBMBpJCkRtdC0AAKuvrqHend2ZHxUYTyJqXhULJ-4r2lpCzd1HLC_lrJhlYjFjZmEzMjE4MmZkNTJlNmMyYzU0NTA1ZDdjNzg0OBIBKgAABiB-nAE3qdRPHz7RCdSxUnU3cqHJ6MV52TXfu5u4OptLEw@esm.ubuntu.com/ubuntu/pool/ /tmp/tmptlkpg0sx' [exit(100)]. Message: E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/  Could not resolve host: esm.ubuntu.com

E: Download Failed


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.4', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 481, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 74, in new_f
    return f(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 269, in action_enable
    return 0 if _perform_enable(args.name, cfg) else 1
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 246, in _perform_enable
    ret = entitlement.enable(silent_if_inapplicable=silent_if_inapplicable)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 68, in enable
    self.setup_apt_config()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 248, in setup_apt_config
    repo_filename, repo_url, token, repo_suites, aptKey, keyring_file
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 124, in add_auth_apt_repo
    assert_valid_apt_credentials(repo_url, username, password)
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 61, in assert_valid_apt_credentials
    timeout=APT_HELPER_TIMEOUT,
  File "/usr/lib/python3.4/tempfile.py", line 557, in __exit__
    self.close()
  File "/usr/lib/python3.4/tempfile.py", line 564, in close
    self._closer.close()
  File "/usr/lib/python3.4/tempfile.py", line 501, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmptlkpg0sx'
```

**Comment by OddBloke** [comment]
I think the best way around this is to use a TemporaryDirectory, and point apt-helper at a path inside that directory. This looks to be working locally, I just need to rework the tests before I can propose it.
