### ISSUE TITLE
ESM failed to enable, but apt preferences file is removed

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#778]
The `/etc/apt/preferences.d/ubuntu-esm-trusty` file (on trusty) is created on postinst if ESM is **disabled**:
```bash
    if [ ! -e "$ESM_APT_PREF_FILE" ]; then
        ESM_POLICY=`apt-cache policy | grep https://esm.ubuntu.com | awk 'END{print $1}'`
        if [ "500" != "$ESM_POLICY" ]; then  # we are inactive
            cat > $ESM_APT_PREF_FILE <<EOF
# Written by ubuntu-advantage-tools
Package: *
Pin: release o=UbuntuESM, n=trusty
Pin-Priority: never
EOF
        fi
```
This tells apt to never consider packages from ESM for upgrades.
The current client is failing to enable ESM because of the rename work that is still in progress (esm -> esm-infra), but what I noticed is that after the failed attempt to enable ESM, that preferences file is gone:
```diff
--- after-ua-install.list	2019-10-01 14:07:22.390405496 +0000
+++ after-ua-my-attach.list	2019-10-01 14:28:33.086405496 +0000
@@ -84,7 +84,6 @@
 /etc/apt/apt.conf.d/50unattended-upgrades
 /etc/apt/apt.conf.d/51ubuntu-advantage-esm
 /etc/apt/apt.conf.d/20apt-esm-hook.conf
-/etc/apt/preferences.d/ubuntu-esm-trusty
 /etc/apt/trusted.gpg.d/ahasenack-ua-temp.gpg~
 /etc/apt/trusted.gpg.d/ubuntu-esm-v2-keyring.gpg
 /etc/apt/trusted.gpg.d/ahasenack-ua-temp.gpg
```
This means apt upgrade/dist-upgrade is considering ESM packages, but it then fails to download them:
```
...
After this operation, 427 MB of additional disk space will be used.
0% [Working]
Get:1 https://esm.ubuntu.com/ubuntu/ trusty-security/main bash amd64 4.3-7ubuntu1.8+esm1 [575 kB]
Err https://esm.ubuntu.com/ubuntu/ trusty-security/main bash amd64 4.3-7ubuntu1.8+esm1
  HttpError401
...
```
This is the output of `ua status` in this state:
```
ubuntu@trusty-ua:~$ sudo ua status
SERVICE       ENTITLED  STATUS    DESCRIPTION
cc-eal        none      —         Common Criteria EAL2 Provisioning Packages
cis-audit     none      n/a       Center for Internet Security Audit Tools
esm           none      n/a       UA Infra: Extended Security Maintenance
fips          none      —         NIST-certified FIPS modules
fips-updates  none      —         Uncertified security updates to FIPS modules
livepatch     entitled  disabled  Canonical Livepatch service

Enable services with: ua enable <service>

     Account: andreas.hasenack@canonical.com
Subscription: andreas.hasenack@canonical.com
```

**Comment by panlinux** [comment]
And in that exact state, if I try `sudo ua disable esm`, I get this backtrace:
```
$ sudo ua disable esm
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.4', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 460, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 490, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 75, in new_f
    return f(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 221, in action_disable
    ret = 0 if entitlement.disable() else 1
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 91, in disable
    self._cleanup()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 98, in _cleanup
    self.remove_apt_config()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 271, in remove_apt_config
    "machine-access-{}".format(self.name)
AttributeError: 'NoneType' object has no attribute 'get'
```
