### ISSUE TITLE
Failed to attach to staging contract with effectiveTo set

### ISSUE THREAD

**Issue by cmars** [CanonicalLtd/ubuntu-advantage-client#782]
I created a contract on staging today, to which I am unable to attach. I'm getting an error:

```
root@trusty-ua-test:~# ua attach ***redacted***
This machine is now attached to 'cmars-contract-staging'.

Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 397, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 426, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 281, in action_attach
    action_status(args=None, cfg=cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 341, in action_status
    print(ua_status.format_tabular(cfg.status()))
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 260, in status
    self.write_cache('status-cache', status)
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 219, in write_cache
    content = json.dumps(content)
  File "/usr/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2020, 10, 1, 0, 0) is not JSON serializable
```

The contract has an effectiveTo timestamp of `2020-10-01T00:00:00Z` on it... perhaps we haven't tested with contracts that have this field set?

Tested this on trusty, installed the client from the ppa (ppa:canonical-server/ua-client).

**Comment by OddBloke** [comment]
Hey Casey, thanks for the testing! That PPA contains a fairly old version of the client. Could you try again with https://launchpad.net/~canonical-server/+archive/ubuntu/ua-client-daily and let us know if you're still seeing this?

**Comment by cmars** [comment]
@OddBloke Thanks, daily seems to be working, I'll use that for my testing.

**Comment by OddBloke** [comment]
Thanks for the confirmation!
