### ISSUE TITLE
ua attach run into No such file or directory: '/etc/apt/auth.conf.d/90ubuntu-advantage'

### ISSUE THREAD

**Issue by lccnblack** [CanonicalLtd/ubuntu-advantage-client#845]
steps:
1.lxc launch a 14.04 container .inside the container ,do "attach" and "detach" token  successfully
2.on the same host(lxc host) ,start a 14.04 kvm vm .
3.inside the kvm vm ,attach token failed .
details :
test@test2:/var/log$ apt search ubuntu-advantage-tools
Sorting... Done
Full Text Search... Done
ubuntu-advantage-tools/trusty,now 19.6~646~git.96620f1~ubuntu14.04.1 amd64 [installed]
  management tools for Ubuntu Advantage

test@test2:/var/log$ cat /etc/issue
Ubuntu 14.04.6 LTS \n \l

test@test2:~$ sudo ua --debug attach TOKEN
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: File does not exist: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: Reading file: /var/lib/dbus/machine-id
DEBUG: Reading file: /etc/os-release
DEBUG: URL [POST]: https://contracts.canonical.com/v1/context/machines/token, headers: {'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'UA-Client/19.6~646~git.96620f1~ubuntu14.04.1', 'Authorization': 'Bearer C13dHA7qFuZFA6jXTT1mqGmqxAF2Jo'}, data: b'{"os": {"distribution": "Ubuntu", "release": "14.04", "version": "14.04 LTS (Trusty Tahr)", "kernel": "4.4.0-142-generic", "type": "Linux", "series": "trusty"}, "machineId": "5aed92b2b8d57ac9225778f35da6b8a5", "architecture": "x86_64"}'
DEBUG: URL [POST] response: https://contracts.canonical.com/v1/context/machines/token, headers: Server: openresty/1.15.8.2
Date: Wed, 16 Oct 2019 06:33:52 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Trace-Id: 5c47f16c-ead6-49cd-9654-5d0f20c3731c

, data: {'resourceTokens': [{'Type': 'esm-infra', 'Token': 'mAgJhAwoQcrgjDMlQillDWS7TOQjkjBIBMBpJCkRtdC0AASsNZ2SqzrVJ8SOt2MJZ2HA943ieLcbqXqHUJ9WGAEQ1YWVkOTJiMmI4ZDU3YWM5MjI1Nzc4ZjM1ZGE2YjhhNRIBKgAABiCcCp1zNaMjD-6JKWRpxBidrfpsGhjnTvMKhSWeW7CQRA'}], 'machineTokenInfo': {'accountInfo': {'createdAt': '2019-10-16T02:41:09Z', 'id': 'aAVrCWtvAKY3liMfrOceb2YuTycgR1jUEu8UZcLhi-Q0', 'name': 'chuan.li@canonical.com'}, 'contractInfo': {'origin': 'free', 'resourceEntitlements': [{'affordances': {'architectures': ['arm64', 'armhf', 'i386', 'ppc64le', 's390x', 'x86_64'], 'series': ['precise', 'trusty', 'xenial', 'bionic']}, 'directives': {'suites': ['precise', 'trusty-infra-security', 'trusty-infra-updates', 'xenial-infra-security', 'bionic-infra-security'], 'aptKey': '56F7650A24C9E9ECF87C4D8D4067E40313CB4B13', 'aptURL': 'https://esm.ubuntu.com'}, 'obligations': {'enableByDefault': True}, 'type': 'esm-infra', 'series': {'precise': {'directives': {'suites': ['precise'], 'aptKey': '74AE092F7629ACDF4FB17310B4C2AF7A67C7A026'}}, 'trusty': {'directives': {'suites': ['trusty-infra-security', 'trusty-infra-updates']}}, 'xenial': {'directives': {'suites': ['xenial-infra-security'], 'aptKey': '3CB3DF682220A643B43065E9B30EDAA63D8F61D0'}, 'obligations': {'enableByDefault': False}}, 'bionic': {'directives': {'suites': ['bionic-infra-security'], 'aptKey': '2926E7D347A1955504000A983121D2531EF59819'}, 'obligations': {'enableByDefault': False}}}, 'entitled': True}, {'affordances': {'kernelFlavors': ['generic', 'lowlatency', 'oem', 'aws'], 'minKernelVersion': '4.4', 'architectures': ['x86_64'], 'tier': 'stable', 'series': ['trusty', 'xenial', 'bionic']}, 'directives': {'remoteServer': 'https://livepatch.canonical.com', 'caCerts': ''}, 'obligations': {'enableByDefault': True}, 'type': 'livepatch', 'series': {'trusty': {'obligations': {'enableByDefault': False}}}, 'entitled': True}, {'obligations': {'enableByDefault': False}, 'affordances': {'supportLevel': 'n/a'}, 'type': 'support', 'entitled': True}], 'createdAt': '2019-10-16T02:41:37.90243Z', 'allowances': [{'value': 3, 'metric': 'attached-machines'}], 'id': 'cASsNZ2SqzrVJ8SOt2MJZ2HA943ieLcbqXqHUJ9WGAEQ', 'effectiveFrom': '2019-10-16T02:41:37.902431Z', 'createdBy': '', 'name': 'chuan.li@canonical.com'}, 'machineId': '5aed92b2b8d57ac9225778f35da6b8a5'}, 'machineToken': 'mAgJhAwoQcrgjDMlQillDWS7TOQjkjBIBMBpJCkRtdC0AASsNZ2SqzrVJ8SOt2MJZ2HA943ieLcbqXqHUJ9WGAEQ1YWVkOTJiMmI4ZDU3YWM5MjI1Nzc4ZjM1ZGE2YjhhNRIBKgAABiCcCp1zNaMjD-6JKWRpxBidrfpsGhjnTvMKhSWeW7CQRA', 'availableResources': [{'available': True, 'name': 'esm-infra'}, {'available': True, 'name': 'livepatch'}, {'available': True, 'name': 'support'}]}
DEBUG: Writing file: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-access-support.json
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-access-livepatch.json
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-access-esm-infra.json
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /var/lib/dbus/machine-id
DEBUG: URL [GET]: https://contracts.canonical.com/v1/resources/esm-infra/context/machines/5aed92b2b8d57ac9225778f35da6b8a5, headers: {'accept': 'application/json', 'content-type': 'application/json', 'user-agent': 'UA-Client/19.6~646~git.96620f1~ubuntu14.04.1', 'Authorization': 'Bearer mAgJhAwoQcrgjDMlQillDWS7TOQjkjBIBMBpJCkRtdC0AASsNZ2SqzrVJ8SOt2MJZ2HA943ieLcbqXqHUJ9WGAEQ1YWVkOTJiMmI4ZDU3YWM5MjI1Nzc4ZjM1ZGE2YjhhNRIBKgAABiCcCp1zNaMjD-6JKWRpxBidrfpsGhjnTvMKhSWeW7CQRA'}, data: None
DEBUG: URL [GET] response: https://contracts.canonical.com/v1/resources/esm-infra/context/machines/5aed92b2b8d57ac9225778f35da6b8a5, headers: Server: openresty/1.15.8.2
Date: Wed, 16 Oct 2019 06:33:54 GMT
Content-Type: application/json
Content-Length: 1143
Connection: close
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15724800; includeSubDomains
X-Trace-Id: dcbb16af-2526-45ff-a67f-ebf63764facb

, data: {'resourceToken': 'mAgJhAwoQcrgjDMlQillDWS7TOQjkjBIBMBpJCkRtdC0AASsNZ2SqzrVJ8SOt2MJZ2HA943ieLcbqXqHUJ9WGAEQ1YWVkOTJiMmI4ZDU3YWM5MjI1Nzc4ZjM1ZGE2YjhhNRIBKgAABiCcCp1zNaMjD-6JKWRpxBidrfpsGhjnTvMKhSWeW7CQRA', 'entitlement': {'affordances': {'architectures': ['arm64', 'armhf', 'i386', 'ppc64le', 's390x', 'x86_64'], 'series': ['precise', 'trusty', 'xenial', 'bionic']}, 'directives': {'suites': ['precise', 'trusty-infra-security', 'trusty-infra-updates', 'xenial-infra-security', 'bionic-infra-security'], 'aptKey': '56F7650A24C9E9ECF87C4D8D4067E40313CB4B13', 'aptURL': 'https://esm.ubuntu.com'}, 'obligations': {'enableByDefault': True}, 'type': 'esm-infra', 'series': {'precise': {'directives': {'suites': ['precise'], 'aptKey': '74AE092F7629ACDF4FB17310B4C2AF7A67C7A026'}}, 'trusty': {'directives': {'suites': ['trusty-infra-security', 'trusty-infra-updates']}}, 'xenial': {'directives': {'suites': ['xenial-infra-security'], 'aptKey': '3CB3DF682220A643B43065E9B30EDAA63D8F61D0'}, 'obligations': {'enableByDefault': False}}, 'bionic': {'directives': {'suites': ['bionic-infra-security'], 'aptKey': '2926E7D347A1955504000A983121D2531EF59819'}, 'obligations': {'enableByDefault': False}}}, 'entitled': True}}
DEBUG: Writing file: /var/lib/ubuntu-advantage/private/machine-access-esm-infra.json
DEBUG: Reading file: /etc/os-release
DEBUG: Using UA client configuration file at /etc/ubuntu-advantage/uaclient.conf
DEBUG: Reading file: /etc/ubuntu-advantage/uaclient.conf
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-token.json
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-access-support.json
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-access-livepatch.json
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /var/lib/ubuntu-advantage/private/machine-access-esm-infra.json
DEBUG: Reading file: /etc/os-release
DEBUG: Ran cmd: apt-cache policy, rc: 0 stderr: b''
DEBUG: Reading file: /etc/os-release
Enabling default service esm-infra
DEBUG: Ran cmd: apt-cache policy, rc: 0 stderr: b''
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /etc/os-release
DEBUG: Reading file: /etc/os-release
DEBUG: Ran cmd: apt-cache policy, rc: 0 stderr: b''
DEBUG: Writing file: /etc/apt/sources.list.d/ubuntu-esm-infra-trusty.list
DEBUG: Writing file: /etc/apt/auth.conf.d/90ubuntu-advantage
ERROR: [Errno 2] No such file or directory: '/etc/apt/auth.conf.d/90ubuntu-advantage'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 272, in request_updated_contract
    allow_enable=allow_enable,
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 203, in process_entitlement_delta
    orig_access, deltas, allow_enable=allow_enable
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 140, in process_contract_deltas
    if super().process_contract_deltas(orig_access, deltas, allow_enable):
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/base.py", line 311, in process_contract_deltas
    self.enable()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 68, in enable
    self.setup_apt_config()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 245, in setup_apt_config
    repo_filename, repo_url, token, repo_suites, self.repo_key_file
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 159, in add_auth_apt_repo
    add_apt_auth_conf_entry(repo_url, username, password)
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 203, in add_apt_auth_conf_entry
    util.write_file(apt_auth_file, "\n".join(new_lines), mode=0o600)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 524, in write_file
    with open(filename, "wb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/auth.conf.d/90ubuntu-advantage'
Unexpected error handling Ubuntu Advantage contract changes

**Comment by panlinux** [comment]
Does the kvm vm not have the /etc/apt/auto.conf.d directory? It should be part of apt 1.0.1ubuntu2.23

**Comment by jpseara** [comment]
Running into this same exact issue. Similar environment.

**Comment by panlinux** [comment]
You need 19.6~651~git.f93c6aa or later, if using the daily builds ppa

**Comment by jpseara** [comment]
Not using the dailys, as "call for testing!" request instructed to use "canonical-server/ua-client" PPA.

Also, I was able to workaround this issue by manually creating the auth.conf.d directory. Only to run into a different issue: https://github.com/CanonicalLtd/ubuntu-advantage-client/issues/859

**Comment by panlinux** [comment]
Understood. I just meant that it's fixed now in the code.

**Comment by powersj** [comment]
I have copied the newest version to the ua-client ppa. Closing this bug.
