### ISSUE TITLE
Traceback when logging in to UA site

### ISSUE THREAD

**Issue by rfinnie** [CanonicalLtd/ubuntu-advantage-client#861]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/run.demo.haus-demos/ubuntu-com-canonical-web-and-design-pr-5769.run.demo.haus/webapp/views.py", line 75, in advantage
    ).json()["accounts"]
KeyError: 'accounts'
```

**Comment by powersj** [comment]
I believe this is the same as #840. This was the workaround posted there:

I believe this is due to having staging SSO cookie set. Either flush your cookies or visit https://ubuntu-com-canonical-web-and-design-pr-5769.run.demo.haus/logout then go back to https://ubuntu-com-canonical-web-and-design-pr-5769.run.demo.haus/advantage and login. If this issue persists please let me know here.
