### ISSUE TITLE
Noisy traceback logs on ua status on disconnected machine

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#868]
The traceback referenced in ubuntu-advantage.log on connectivity errors is unhelpful for the following reasons:

- It doesn't properly report generic connectivity issues, but rather a symptom "[Errno -2] Name or service not known
- It's traceback is long, convoluted (with two traces of failures) making it very verbose and harder to find the actual point of failure
 - The log message doesn't match what the user sees at the console, so they won't know intuitively what to look for in the log files
- The  log doesn't actually report the url or service endpoint suffered from connectivty issues

Let's propose to log the same simple connectivity message error as seen by the user on the CLI, and the url in question as it'll be easier to read in logs what part of uaclient codebase failed in the actually failed.

Steps to reproduce:
```
cat > upgrade-uaclient.yaml <<EOF
#cloud-config
package_update: true
package_upgrade: true
apt_sources:
        - source: "deb [trusted=yes] http://ppa.launchpad.net/canonical-server/ua-client-daily/ubuntu $RELEASE main"
runcmd:
        - apt-get dist-upgrade --assume-yes --force-yes
EOF

lxc launch ubuntu-daily:trusty dev-t -c user.user-data="$(cat upgrade-uaclient.yaml )"
lxc exec dev-t ip link set down eth0
lxc exec dev-t ua status

cat /var/log/ubuntu-advantage.log



2019-10-21 17:33:27,754 - cli.py:(505) [ERROR]: [Errno -2] Name or service not known
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1182, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1125, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1163, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1121, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 951, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 886, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 1260, in connect
    super().connect()
  File "/usr/lib/python3.4/http/client.py", line 863, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/serviceclient.py", line 52, in request_url
    url=url, data=data, headers=headers, method=method
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 385, in readurl
    resp = request.urlopen(req)
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 463, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 481, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1225, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.4/urllib/request.py", line 1184, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 497, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 532, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 432, in action_status
    print(ua_status.format_tabular(cfg.status()))
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 322, in status
    response = self._unattached_status()
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 223, in _unattached_status
    resources = get_available_resources(self)
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 291, in get_available_resources
    resources = client.request_resources()
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 104, in request_resources
    API_V1_RESOURCES + "?" + urllib.parse.urlencode(query_params)
  File "/usr/lib/python3/dist-packages/uaclient/serviceclient.py", line 63, in request_url
    e, code=getattr(e, "code", None), headers=headers, url=url
uaclient.util.UrlError: [Errno -2] Name or service not known
```

**Comment by OddBloke** [comment]
Can we get an example of the traceback, please?

**Comment by OddBloke** [comment]
(And, also, why you think this is noise rather than useful debugging information. Thanks!)

**Comment by OddBloke** [comment]
> * It doesn't properly report generic connectivity issues, but rather a symptom "[Errno -2] Name or service not known

This isn't a symptom, this is the underlying cause of the error. That's useful debugging information.

> * Its traceback is long, convoluted (with two traces of failures) making it very verbose and harder to find the actual point of failure

The multiple tracebacks indicate the source of the issue being seen, I don't see how we could find the actual point of failure _without_ them. For example, in this case, we know that the "Name or service not known" is coming from `_socket.getaddrinfo` so it's probably a low-level issue with DNS configuration/connectivity, rather than a protocol level issue in the HTTP library. (Odds are that we could guess that based on this specific error message, but that is not necessarily true of every error message we might see from somewhere in the stack.)

> * The log message doesn't match what the user sees at the console, so they won't know intuitively what to look for in the log files

This sounds like you're saying the answer to https://github.com/CanonicalLtd/ubuntu-advantage-client/pull/860/files#r336225174 was actually `ua_status.MESSAGE_CONNECTIVITY_ERROR`. This would definitely be an improvement, we should do it.

> * The log doesn't actually report the url or service endpoint suffered from connectivty issues

+1 on improving that too.
