### ISSUE TITLE
Error shown during attach-premium, but attachment seems to succeed nonetheless

### ISSUE THREAD

**Issue by alnvdl** [CanonicalLtd/ubuntu-advantage-client#938]
Detached:

    $ sudo ua detach
    Detach will disable the following service:
        esm-infra
    Are you sure? (y/N) y
    Updating package lists
    This machine is now detached

Then tried attaching again (against the contract service in staging), which apparently failed:

    $ sudo ua attach-premium
    Enabling default service esm-infra
    Updating package lists
    ESM Infra enabled
    Traceback (most recent call last):
      File "/usr/bin/ua", line 9, in <module>
        load_entry_point('ubuntu-advantage-tools==19.6', 'console_scripts', 'ubuntu-advantage')()
      File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 572, in wrapper
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 612, in main
        return args.action(args, cfg)
      File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 347, in action_attach_premium
        ua_status.MESSAGE_ATTACH_FAILURE_TMPL.format(url=cfg.contract_url)
    AttributeError: 'module' object has no attribute 'MESSAGE_ATTACH_FAILURE_TMPL'

But it seems to have worked (?):

    $ sudo ua status
    SERVICE       ENTITLED  STATUS    DESCRIPTION
    cc-eal        no        -         Common Criteria EAL2 Provisioning Packages
    cis-audit     no        -         Center for Internet Security Audit Tools
    esm-infra     yes       enabled   UA Infra: Extended Security Maintenance
    fips          no        -         NIST-certified FIPS modules
    fips-updates  no        -         Uncertified security updates to FIPS modules
    livepatch     yes       n/a       Available with the HWE kernel

    Enable services with: ua enable <service>

                    Account: 022588101030
               Subscription: 022588101030
                Valid until: n/a
    Technical support level: essential

**Comment by alnvdl** [comment]
Not seeing this anymore with the latest client and images, closing this.
