### ISSUE TITLE
auto-attach assumes that /sys/hypervisor/uuid exists on EC2 instances

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#946]
On a `m5.large`, we see:

```
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.7', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 576, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 616, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 89, in new_f
    return f(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 52, in new_f
    return f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 387, in action_auto_attach
    token = _get_contract_token_from_cloud_identity(cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 369, in _get_contract_token_from_cloud_identity
    instance = identity.cloud_instance_factory()
  File "/usr/lib/python3/dist-packages/uaclient/clouds/identity.py", line 60, in cloud_instance_factory
    if not instance.is_viable:
  File "/usr/lib/python3/dist-packages/uaclient/clouds/aws.py", line 26, in is_viable
    hypervisor_uuid = util.load_file(SYS_HYPERVISOR_PRODUCT_UUID)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 373, in load_file
    with open(filename, "rb") as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/sys/hypervisor/uuid'
```

The fact that a traceback leaks out is an issue, but the more important problem is that we do not auto-attach.

**Comment by OddBloke** [comment]
I've reproduced this on bionic also.

**Comment by OddBloke** [comment]
I've built packages into the daily PPA and confirmed that they all look good; copying to the premium PPA now.
